services:

  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: flask-app
    expose:
      - "8000"


  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"

    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - app
